'use strict';

const mongoose = require('mongoose');

/**
 * GeoCoordinates sub-schema.
 * Stores the geographic origin/destination as a GeoJSON Point so that
 * the data can optionally be indexed and queried spatially.
 */
const CoordinatesSchema = new mongoose.Schema(
  {
    lat:  { type: Number, required: true, min: -90,  max: 90  },
    long: { type: Number, required: true, min: -180, max: 180 },
  },
  { _id: false }   // embedded doc – no separate _id needed
);

/**
 * ThreatEvent schema.
 * Each document represents a single, discrete cyber-attack event detected
 * by the SIEM engine.
 */
const ThreatEventSchema = new mongoose.Schema(
  {
    // ── Network identifiers ───────────────────────────────────────────────
    source_ip: {
      type:     String,
      required: true,
      trim:     true,
      match:    [
        /^(\d{1,3}\.){3}\d{1,3}$/,
        'source_ip must be a valid IPv4 address',
      ],
    },
    target_ip: {
      type:     String,
      required: true,
      trim:     true,
      match:    [
        /^(\d{1,3}\.){3}\d{1,3}$/,
        'target_ip must be a valid IPv4 address',
      ],
    },

    // ── Geographic context ────────────────────────────────────────────────
    source_country: {
      type:     String,
      required: true,
      trim:     true,
      maxlength: 100,
    },
    target_country: {
      type:     String,
      required: true,
      trim:     true,
      maxlength: 100,
    },

    /**
     * Attacker's geographic coordinates used for globe/map visualization.
     * Stored as { lat, long } for simplicity; extend to GeoJSON if you
     * need $geoNear queries.
     */
    coordinates: {
      type:     CoordinatesSchema,
      required: true,
    },

    // ── Attack classification ─────────────────────────────────────────────
    attack_type: {
      type:     String,
      required: true,
      enum: [
        'SSH Brute Force',
        'SQL Injection',
        'DDoS',
        'Port Scan',
        'Malware',
        'Phishing',
        'Man-in-the-Middle',
        'Zero-Day Exploit',
        'Ransomware',
        'DNS Spoofing',
      ],
    },
    severity: {
      type:     String,
      required: true,
      enum:     ['Low', 'Medium', 'High', 'Critical'],
      default:  'Medium',
    },

    // ── Metadata ──────────────────────────────────────────────────────────
    /** Human-readable event description generated by the SIEM engine. */
    description: {
      type:    String,
      trim:    true,
      maxlength: 500,
    },

    /** Count of repeated attempts for brute-force / volumetric attacks. */
    packet_count: {
      type: Number,
      min:  1,
    },

    timestamp: {
      type:    Date,
      default: Date.now,
      index:   true,   // fast range queries on time-series dashboards
    },

    // ── SOAR status ───────────────────────────────────────────────────────
    /**
     * Lifecycle status of this threat event, managed by SOAR playbooks.
     *   Active    — default; event is live and unaddressed.
     *   Mitigated — a playbook (e.g. Block IP) has been executed successfully.
     *   Dismissed — analyst marked as a false positive.
     */
    status: {
      type:    String,
      enum:    ['Active', 'Mitigated', 'Dismissed'],
      default: 'Active',
      index:   true,
    },

    /** ISO timestamp set when status transitions away from 'Active'. */
    mitigated_at: {
      type: Date,
    },

    /** Which playbook was executed, e.g. 'block-ip'. */
    mitigated_by: {
      type:      String,
      maxlength: 100,
    },
  },
  {
    // ── Schema-level options ──────────────────────────────────────────────
    timestamps:  { createdAt: 'created_at', updatedAt: false },
    versionKey:  false,   // remove __v from documents
    collection:  'threat_events',
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────
// Compound index for common dashboard queries: filter by severity then sort by time
ThreatEventSchema.index({ severity: 1, timestamp: -1 });
// Fast lookup for "all attacks from a given country" in geo-analytics view
ThreatEventSchema.index({ source_country: 1, timestamp: -1 });
// Support filtering by attack type in the events table
ThreatEventSchema.index({ attack_type: 1, timestamp: -1 });
// SOAR Block-IP playbook: updateMany({ source_ip, status:'Active' }) — critical for fast mitigation
ThreatEventSchema.index({ source_ip: 1, status: 1 });
// Socket history query: find({}).sort({timestamp:-1}).limit(50) — covered by this index
ThreatEventSchema.index({ timestamp: -1 });

// ── Instance helpers ──────────────────────────────────────────────────────
/**
 * Returns a lean, serialisation-friendly object suited for Socket.io payloads.
 * Keeps the document small to avoid saturating the WebSocket channel.
 */
ThreatEventSchema.methods.toSocketPayload = function () {
  return {
    id:             this._id,
    source_ip:      this.source_ip,
    target_ip:      this.target_ip,
    source_country: this.source_country,
    target_country: this.target_country,
    coordinates:    this.coordinates,
    attack_type:    this.attack_type,
    severity:       this.severity,
    description:    this.description,
    packet_count:   this.packet_count,
    timestamp:      this.timestamp,
    status:         this.status,
    mitigated_at:   this.mitigated_at,
    mitigated_by:   this.mitigated_by,
  };
};

const ThreatEvent = mongoose.model('ThreatEvent', ThreatEventSchema);

module.exports = ThreatEvent;
